require "rake/clean"

SRC = FileList["*.in"]
OUT = SRC.ext('out')

rule ".out" => ".in" do |t|
  c = []
  c << "echo 'hostname: '`hostname`"
  c << "echo 'pwd:      '`pwd`"
  if defined? Pwrake
    c << "echo 'filenode: '`gfwhere #{Pwrake::GfarmSSH.gf_pwd}/#{t.prerequisites[0]}`"
  end
  s = c.join("\n  ")
  sh "(\n  #{s}\n) > #{t.name}"
end

task :default => OUT

CLEAN.include("*.out")
