require "rake/clean"

SRC = FileList["*.in"]
OUT = SRC.ext('out')

rule ".out" => ".in" do |t|
  sh "(
    echo 'hostname: '`hostname`
    echo 'filenode: '`gfwhere #{Pwrake::GfarmSSH.gf_pwd}/#{t.prerequisites[0]}`
    echo 'pwd:      '`pwd`
    ) > #{t.name}"
end

task :default => OUT

CLEAN.include("*.out")
