load "clean.rake"

task :default do
  puts "
usage:
  ./pwrake clean
  ./pwrake -f affinity.rake
  ./pwrake -f affinity.rake FS=gfarm NODEFILE=tsukuba4 LOG=`date +%Y%m%d%H%M%S`
  ./pwrake -f partition.rake
  ./pwrake -f partition.rake FS=gfarm NODEFILE=tsukuba4 LOG=`date +%Y%m%d%H%M%S`

"
end
