require 'rake/clean'
require './montage_tools.rb'

# Default task
task :default => "mosaic.jpg"
#task :default => "shrunk.jpg"

if ENV['MONTAGE_ORIGINAL']
  Montage.original_workflow = true
  puts "Montage.original_workflow = true"
else
  Montage.original_workflow = false
  puts "Montage.original_workflow = false"
end

# Program path
dir=Dir.glob(Dir.pwd+"/Montage_*/bin")
ENV['PATH'] = "#{dir.last}:"+ENV['PATH']

# Directory of input files
INPUT_DIR = ENV["INPUT_DIR"] || "m101/rawdir"
# Parameter file for the coorinate of a result image
REGION_HDR = ENV["REGION_HDR"] || "m101/template.hdr"
#REGION_HDR = "#{INPUT_DIR}/region.hdr"
# Parameter file for a shrunk image
SHRUNK_HDR = ENV["SHRUNK_HDR"] || "#{INPUT_DIR}/shrunken.hdr"
# List of input FITS image files
SRC_FITS = FileList["#{INPUT_DIR}/*.fits"]

# Get image size
if File.exist?(REGION_HDR)
  File.open(REGION_HDR) do |f|
    while l=f.gets
      eval l if /(NAXIS[12])\s*=\s*(\d+)/ =~ l
    end
  end

  # Tile parameter
  TILE_NX = ENV["TILE_NX"]
  TILE_NY = ENV["TILE_NY"]
  TILE_PIXEL=1000
  SHRINK_FACTOR=10
  NX = [(TILE_NX || NAXIS1/TILE_PIXEL).to_i, 10].max
  NY = [(TILE_NY || NAXIS2/TILE_PIXEL).to_i, 10].max
  puts "NX=#{NX}, NY=#{NY}"
end

# Make directories
mkdir_p ["p","d","c","s","t"]

### Projection
P_IMGTBL=[]
P_FITS=[]
SRC_FITS.each do |src|
  prj = src.sub(/^(.*?)([^\/]+).fits/,'p/\2.p.fits')
  file prj => [src,REGION_HDR] do |t|
    sh "mProjectPP #{src} #{prj} #{REGION_HDR}" do |ok,status|
      Montage.collect_imgtbl(t, P_IMGTBL) if ok
    end
  end
  P_FITS << prj
end

### List projected files
file "pimages.tbl" => P_FITS do
  Montage.put_imgtbl(P_IMGTBL, "p", "pimages.tbl")
end

### List overlapping images
file "diffs.tbl" => "pimages.tbl" do
  sh "mOverlaps pimages.tbl diffs.tbl"
end

### Fit the difference of overlapping images
file "fits.tbl" => "diffs.tbl" do
  # Read diffs.tbl
  DIF_TBL = Montage.read_overlap_tbl("diffs.tbl")
  # Write a list of fit-result files
  Montage.write_fittxt_tbl("fittxt.tbl", DIF_TBL)

  DIFF_FITS=[]
  FIT_TBL=[]
  DIF_TBL.each do |c|
    p1 = "p/"+c[2]
    p2 = "p/"+c[3]
    DIFF_FITS << dif_fit = "d/"+c[4]
    file dif_fit => [p1,p2,REGION_HDR] do |t|
      x1,x2,rh = t.prerequisites
      # Calculate the difference of two images
      sh "mDiff #{x1} #{x2} #{t.name} #{REGION_HDR}" do |ok,status|
        # Fit image difference
        Montage.fitplane(c[0..1], t, FIT_TBL) if ok
      end
    end
  end

  # List fit parameters
  task :fits_tbl_invoke => DIFF_FITS do
    Montage.write_fits_tbl(FIT_TBL, "fittxt.tbl", "fits.tbl")
  end.invoke

  task "fits.tbl" => :fits_tbl_invoke
end

### Background modeling
file "corrections.tbl"=>["fits.tbl","pimages.tbl"] do
  sh "mBgModel pimages.tbl fits.tbl corrections.tbl"
end

### Background correction
file "cimages.tbl" => ["corrections.tbl","pimages.tbl"] do
  C_IMGTBL=[]
  C_FITS=[]

  FileList["p/*.p.fits"].each do |s|
    dst = s.sub(/p\/(.*)\.p\.fits/, 'c/\1.c.fits')
    file dst => [s,"pimages.tbl","corrections.tbl"] do |t|
      p0,p1,p2 = t.prerequisites
      src = p0.sub(/p\//, '')
      sh "(cd p; mBackground -t #{src} ../#{t.name} ../#{p1} ../#{p2})" do |ok,status|
        Montage.collect_imgtbl(t, C_IMGTBL) if ok
      end
    end
    C_FITS << dst
  end

  # List background-corrected images
  task :cimages_invoke => C_FITS do
    Montage.put_imgtbl(C_IMGTBL, "c", "cimages.tbl")
  end.invoke

  task "cimages.tbl" => :cimages_invoke
end

### tile region
file "simages.tbl" => "cimages.tbl" do
  S_IMGTBL=[]
  S_FITS=[]

  # Iterate over NX x NY tiles
  NY.times do |iy|
    NX.times do |ix|
      # Divide into tile regions
      tile_hdr = "t/tile_#{ix}_#{iy}.hdr"
      file tile_hdr => ["cimages.tbl",REGION_HDR,"t"] do |t|
        opt = "#{NX} #{NY} #{ix} #{iy} 50 50"
        sh "mTileHdr #{t.prerequisites[1]} #{t.name} #{opt}"
      end

      # List images covering each tile
      tile_tbl = tile_hdr.ext('tbl')
      file tile_tbl => [tile_hdr,"cimages.tbl"] do |t|
        sh "mCoverageCheck cimages.tbl #{t.name} -header #{t.prerequisites[0]}"
      end

      # Combine images in each tile
      tile_fits = tile_hdr.ext('t.fits')
      file tile_fits => [tile_tbl,tile_hdr] do |t|
        a = t.prerequisites.join(" ")
        sh "mAdd -e -p c #{a} #{t.name} "
      end

      # Shrink each tile image
      shrunk_fits = tile_fits.sub(/t\/(.*)\.t\.fits/, 's/\1.s.fits')
      file shrunk_fits => [tile_fits,tile_tbl] do |t|
        sh "mShrink #{t.prerequisites[0]} #{t.name} #{SHRINK_FACTOR}"
        Montage.collect_imgtbl(t, S_IMGTBL)
      end
      S_FITS << shrunk_fits
    end
  end

  # List shrunk images
  task :simages_invoke => S_FITS do
    Montage.put_imgtbl(S_IMGTBL, "s", "simages.tbl")
  end.invoke

  task "simages.tbl" => :simages_invoke
end

### Add all the images
file "mosaic.fits" => ["cimages.tbl", REGION_HDR] do |t|
  sh "mAdd -p c #{t.prerequisites.join(' ')} #{t.name}"
end

### Convert the result FITS image to JPEG image
file "mosaic.jpg" => "mosaic.fits" do |t|
  sh "mJPEG -ct 0 -gray #{t.prerequisites[0]} -1.5s 60s gaussian -out #{t.name}" do |*a| end
end

### Add all the images
file "shrunk.fits" => ["simages.tbl", SHRUNK_HDR] do |t|
  sh "mAdd -n -e -p s #{t.prerequisites.join(' ')} #{t.name}"
end

### Convert the result FITS image to JPEG image
file "shrunk.jpg" => ["shrunk.fits"] do |t|
  sh "mJPEG -ct 0 -gray #{t.prerequisites[0]} -1.5s 60s gaussian -out #{t.name}" do |*a| end
end

CLEAN.include %w[ p d c s t ]
CLEAN.include %w[ pimages.tbl cimages.tbl simages.tbl ]
CLEAN.include %w[ diffs.tbl fits.tbl fittxt.tbl corrections.tbl ]
CLOBBER.include %w[ mosaic.fits mosaic_area.fits mosaic.jpg ]
CLOBBER.include %w[ shrunk.fits shrunk_area.fits shrunk.jpg ]

# creat DAG image
task :graph => "shrunk.jpg" do
  require "pwrake/graph"
  g = Pwrake::Graphviz.new
  g.trace
  g.write("graph.dot")
end
